ingress:
  enabled: true
  nginx: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-max-body-size: 150M
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 96k
    cert-manager.io/cluster-issuer: letsencrypt-production
  tls:
    - hosts:
        - <your_budibase_hostname>
      secretName: <your_budibase_hostname>
  hosts:
    - host: <your_budibase_hostname>
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: proxy-service
              port:
                number: 10000
services:
  objectStore:
    storage: 1Gi
  redis:
    storage: 1Gi
couchdb:
  image:
    repository: couchdb
    tag: 3.1.0
    pullPolicy: IfNotPresent
