# Keycloak
keycloakserviceAdminUsername: "realmadmin"
keycloakserviceAdminPassword: "Testtest!12"
keycloakserviceTechnicalUsername: "technical"
keycloakserviceTechnicalPassword: "Testtest!12"
online-counseling-keycloak:
  keycloakDbUser: "keycloak"
  keycloakDbPassword: "keycloak"

global:
  # Secrets MariaDB
  mysqlRootPassword: "root"
  springLiquibasePassword: "liquibase"
  springLiquibaseUser: "liquibase"
  agencyServiceSpringDatasourcePassword: "agencyservice"
  agencyServiceSpringDatasourceUsername: "agencyservice"
  messageServiceSpringDatasourceUsername: "messageservice"
  messageServiceSpringDatasourcePassword: "messageservice"
  userServiceSpringDatasourceUsername: "userservice"
  userServiceSpringDatasourcePassword: "userservice"
  uploadServiceSpringDatasourceUsername: "uploadservice"
  uploadServiceSpringDatasourcePassword: "uploadservice"
  tenantServiceSpringDatasourceUsername: "tenantservice"
  tenantServiceSpringDatasourcePassword: "tenantservice"
  consultingTypeServiceSpringDatasourceUsername: "consultingtypeservice"
  consultingTypeServiceSpringDatasourcePassword: "consultingtypeservice"
  appointmentServiceSpringDatasourceUsername: "appointmenteservice"
  appointmentServiceSpringDatasourcePassword: "appointmenteservice"
  keycloakDbUser: "keycloak"
  keycloakDbPassword: "keycloak"
  # Secrets MongoDB
  mongoInitDbRootUsername: "admin"
  mongoInitDbRootPassword: "admin"
  nosqlclientMongoUsername: "nosqlclient"
  nosqlclientMongoPassword: "nosqlclient"
  rocketchatMongoUsername: "rocketchat"
  rocketchatMongoPassword: "rocketchat"
  oplogMongoUsername: "oplog"
  oplogMongoPassword: "oplog"
  statisticsMongoUser: "statistics"
  statisticsMongoPass: "statistics"
  rabbitStatisticsUser: "statistics"
  rabbitStatisticsPassword: "statistics"
  consultingTypeMongoUser: "consulting_types"
  consultingTypeMongoPass: "consulting_types"
  masterkey: "local"

# LDAP
online-counseling-open-ldap:
  adminPassword: "admin"
  configPassword: "config"

rocketTechnicalUsername: "rocket-chat-technical-user"
rocketTechnicalPassword: "technical"
rocketSystemuserUsername: "system1"
rocketSystemuserPassword: "system"

mailExchangeUser: ""
mailExchangePassword: ''

serviceEncryptionAppkey: "DaS-HiEr-iSt-eIn-bEiSpIeL"

online-counseling-videobackend:
  jicofoComponentSecret: "9ea69e051020adb6524bbec8d88e670f"
  jicofoAuthUser: "focus"
  jicofoAuthPassword: "cb7a95bf9671bff5afffd931e566e2dd"
  jvbAuthPassword: "6ba13a7ae9fa26809a3705273d568c5e"
  jvbAuthUser: "jvb"
  jibriRecorderPassword: "777dc0295b984503ab6e02e105bac80f"
  jibriRecorderUser: "recorder"
  jibriXmppPassword: "34167bb5be4998526ee2ae1a82504643"
  jibriXmppUser: "jibri"
  jigasiXmppPassword: "53b2b722bce988cf2776198553143bca"
  jigasiXmppUser: "jigasi"
  jwtAcceptedAudiences: "my_server1"
  jwtAcceptedIssuers: "my_app_client"
  jwtAppId: "meet.jitsi"
  jwtAppSecret: "ca464fd202c74dc92139765ac798980204c4c1d3e8b69494ef897313fe58b936"
  turnCredentials: "example"

videoCallSecurityJwtAudience: "my_server1"
videoCallSecurityJwtIssuer: "my_app_client"
videoCallSecurityJwtSubject: "meet.jitsi"
videoCallSecurityJwtSecret: "ca464fd202c74dc92139765ac798980204c4c1d3e8b69494ef897313fe58b936"

online-counseling-rabbitmq:
  rabbitDefaultPass: "admin"
  rabbitDefaultUser: "admin"

# Kibana
online-counseling-kibana:
  kibanaConfig:
    kibana.yml: |
      elasticsearch:
        hosts:
         - "http://elasticsearch.develop:9200"
        serviceAccountToken: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYXRva2VuOnFSZTdJblZaU3JDMVNwTmxFQm40Wnc"
      xpack:
        encryptedSavedObjects:
          encryptionKey: 866cb03e9b2d5c4f23bfb8ae72113d13
        reporting:
          encryptionKey: 7fb9e63caffbd78d59bccf0aecca4312
        security:
          encryptionKey: e88b4a2a392bde1ee1f59af9f43b5440
  kibanaEncryptionKey: "9wonFxmvmSeGr0kgrvQKRGjS6LVZhVO_Awkfe0IGaY3NDpaPaj"

online-counseling-backup:
  mysqlRootPassword: ""
  backupDatabaseUser: ""
  backupBucketAccessKey: ""
  backupBucketSecretKey: ""
  backupMongoDBAdmin: ""
  backupMongoDBAdminPass: ""
  backupGsCloudUserUUID: ""
  backupGsCloudApiToken: ""
  backupGsCloudClusterId: ""