global:
  domainName: "onlineberatung.localhost"
  dockerHostIp: "192.168.65.2"
  enableTls: false
  multitenancyEnabled: false
  statisticsEnabled: "true"
  topicsEnabled: "false"
  demographicsEnabled: "false"
  appointmentsEnabled: false
  counselingToolsEnabled: false
  adminConsoleEnabled: false
  multitenancyWithSingleDomainEnabled: "false"
  initializeDummyData: true
  useExternalMariaDb: false
  settingMainTenantSubdomainForSingleDomainMultitenancy: "not-needed"

# CSRF
csrfCookieProperty: "CSRF-TOKEN"
csrfHeaderProperty: "X-CSRF-TOKEN"
# Keycloak
keycloakRealm: "online-beratung"
keycloakAuthServerUrl: "http://onlineberatung.localhost/auth"
keycloakPrincipalAttribute: "preferred_username"
keycloakserviceAdminClientid: "admin-cli"
keycloakserviceAppClientid: "app"
keycloakserviceTechuserId:  "8294c392-e1e0-405b-ac2f-ba3043cbad3e"
identityOpenidConnectUrl: "/realms/online-beratung/protocol/openid-connect"
identityOtpUrl: "/realms/online-beratung/otp-config"

# Rocketchat
rocketSystemuserId: "hjvBcfWH5vS3KLv27"
rocketCredentialschedulerCron: "0 0 0/1 * * ?"

# Agencyservice
agencyServiceKeycloakResource: "agency-service"

agencyServiceSpringProfilesActive: "dev"
agencyServiceImageName: "ghcr.io/onlineberatung/onlineberatung-agencyservice/onlineberatung-agencyservice"
agencyServiceImageVersion: "develop_20221117_173329"

# ConsultingTypeService
consultingTypesJsonPath : "consulting-type-settings"
consultingTypeServiceImageName: "ghcr.io/onlineberatung/onlineberatung-consultingtypeservice/onlineberatung-consultingtypeservice"
consultingTypeServiceImageVersion: "develop_20221116_164336"
consultingTypeServiceKeycloakResource: "consultingtype-service"

# Frontend
frontendImageName: "ghcr.io/onlineberatung/onlineberatung-frontend-theme/onlineberatung-frontend-theme"
frontendImageVersion: "develop_20221125_101426"

# Live service
liveServiceImageName: "ghcr.io/onlineberatung/onlineberatung-liveservice/onlineberatung-liveservice"
liveServiceImageVersion: "develop_20221117_114908"
liveServiceSpringProfilesActive: "prod"
liveServiceAppBaseUrl: "http://onlineberatung.localhost"

# Mail service
mailServiceSpringProfilesActive: "dev"
springMailHost: "mail.mail"
springMailUsername: "xxx"
springMailPassword: "xxx"
springMailProtocol: "smtp"
springMailDefaultEncoding:  "UTF-8"
mailSender:  "noreply@app.onlineberatung.local"
mailErrorRecipients: "admin@onlineberatung.local"
appImprintUrl: "http://onlineberatung.localhost/impressum"
appDataprivacyUrl: "http://onlineberatung.localhost/datenschutz"
mailServiceLoggingLevelRoot:  "DEBUG"
mailServiceImageName: "ghcr.io/onlineberatung/onlineberatung-mailservice/onlineberatung-mailservice"
mailServiceImageVersion: "develop_20221116_164215"

# Message service
messageServiceImageName: "ghcr.io/onlineberatung/onlineberatung-messageservice/onlineberatung-messageservice"
messageServiceImageVersion: "develop_20221117_170507"
messageServiceSpringProfilesActive: "local"
messageServiceKeycloakResource: "message-service"
csrfWhitelistHeaderProperty: "local"

# Upload service
uploadServiceImageName: "ghcr.io/onlineberatung/onlineberatung-uploadservice/onlineberatung-uploadservice"
uploadServiceImageVersion: "develop_20221116_164233"
uploadServiceSpringProfilesActive: "local"
uploadServiceKeycloakResource:  "upload-service"

# User service
userServiceImageName: "ghcr.io/onlineberatung/onlineberatung-userservice/onlineberatung-userservice"
userServiceImageVersion: "develop_20221118_105158"
consultantImportFilename: "import/consultants.csv"
consultantImportProtocolFilename: "import/consultants-import.txt"
askerImportFilename: "import/askers.csv"
askerImportWithoutsessionFilename: "import/askers-without-session.csv"
askerImportProtocolFilename: "import/askers-import.txt"
askerImportWelcomeMessageFilename: "import/welcome_consulting_type_[ConsultingType].txt"
askerImportWelcomeMessageFilenameReplaceValue: "[ConsultingType]"
userServiceSpringProfilesActive: "dev"
userServiceKeycloakResource: "user-service"
firebaseConfigurationCredentialsFilePath: "/firebase/firebase-credentials.json"
firebaseConfigurationNotificationMessage: "Du hast eine neue Nachricht erhalten"
userAnonymousDeleteworkflowCron: "* * * * * ?"
userAnonymousDeactivateworkflowCron: "* * * * * ?"
sessionInactiveDeleteworkflowEnabled: "true"
sessionInactiveDeleteworkflowCron: "0 0 * * * ?"
sessionInactiveDeleteworkflowCheckDays: "30"

# Video service
videoServiceImageName: "ghcr.io/onlineberatung/onlineberatung-videoservice/onlineberatung-videoservice"
videoServiceImageVersion: "dockerImage.v.30.release-os"
videoServiceSpringProfilesActive: "dev"
videoCallServerUrl: "http://video.onlineberatung.localhost"
videoCallSecurityJwtAudience: "my_server1"
videoCallSecurityJwtIssuer: "my_app_client"
videoCallSecurityJwtSubject: "meet.jitsi"
videoCallSecurityJwtSecret: "ca464fd202c74dc92139765ac798980204c4c1d3e8b69494ef897313fe58b936"
videoServiceKeycloakResource: "video-service"

# Admin console frontend
adminconsoleImageName: "ghcr.io/virtualidentityag/vi-saas-admin/vi-saas-admin"
adminconsoleImageVersion: "dockerImage.v.341.release-2022-11-21"

# Statistics Service
statisticsServiceImageName: "ghcr.io/onlineberatung/onlineberatung-statisticsservice/onlineberatung-statisticsservice"
statisticsServiceImageVersion: "develop_20221117_155914"

online-counseling-videobackend:
  videoCallServerUrl: "video.onlineberatung.localhost"
  turnHost: "turn.onlineberatung.local"
  turnPort: "443"

online-counseling-backup:
  enableBackup: false