# This is a example deployment workflow for deploying you changes with helm. In this workflow we assume pre configured
# github secrets for your kubernetes cluster id, your kubernetes user id, your kubernetes access token and all secret
# values used for deployment.
name: Deployment Online Beratung Develop example

env:
  K8S_SUBMODULE_VERSION: v0.0.1

on:
  push:
    paths:
      - 'values.yaml'

jobs:
  develop:
    name: Deployment Workflow example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GH_PACKAGE_RELEASE_TOKEN }}

      - name: Adapt .gitmodules for using k8s release
        run: |
          cd k8s
          git checkout tags/$K8S_SUBMODULE_VERSION

      - name: Helm upgrade
        if: contains(steps.changed-files.outputs.modified_files, 'values.yaml')
        uses: ./deployment
        with:
          ENVIRONMENT: develop
          GSCLOUD_CLUSTERID: ${{ secrets.GSCLOUD_CLUSTERID }}
          GSCLOUD_USERID: ${{ secrets.GSCLOUD_USERID }}
          GSCLOUD_TOKEN: ${{ secrets.GSCLOUD_TOKEN }}
          VALUES_SECRET_YAML: ${{ secrets.VALUES_SECRET_YAML }}
